version: "3.8"
services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: random123
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data  # This line ensures data persists

volumes:
  postgres_data:  # Defines the volume
